# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_cpp <- function(xptr, words) {
    .Call(`_kgrams_find_cpp`, xptr, words)
}

length_kgrams_dictionary <- function(xptr) {
    .Call(`_kgrams_length_kgrams_dictionary`, xptr)
}

