# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname preprocess
#' @export
preprocess <- function(input, erase = "[^.?!:;'[:alnum:][:space:]]", lower_case = TRUE) {
    .Call(`_kgrams_preprocess`, input, erase, lower_case)
}

#' @rdname tknz_sent
#' @export
tknz_sent <- function(input, EOS = "[.?!:;]+", keep_first = FALSE) {
    .Call(`_kgrams_tknz_sent`, input, EOS, keep_first)
}

#' @rdname special_tokens
#' @export
EOS <- function() {
    .Call(`_kgrams_EOS`)
}

#' @rdname special_tokens
#' @export
BOS <- function() {
    .Call(`_kgrams_BOS`)
}

#' @rdname special_tokens
#' @export
UNK <- function() {
    .Call(`_kgrams_UNK`)
}

